"""main_db models

Revision ID: 0696b4f3b309
Revises: 
Create Date: 2025-12-01 21:11:16.433017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0696b4f3b309'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('db_type', sa.String(length=50), nullable=False),
    sa.Column('connection_uri', sa.Text(), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('database_name', sa.String(length=150), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('db_metadata', sa.JSON(), nullable=True),
    sa.Column('connection_status', sa.String(length=50), nullable=True),
    sa.Column('last_connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('auto_sync', sa.Boolean(), nullable=True),
    sa.Column('sync_frequency', sa.String(length=30), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('db_type', 'database_name', 'host', 'port', name='uq_db_connection'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_database_connections_id'), 'database_connections', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('database_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('sync_id', sa.String(length=100), nullable=False),
    sa.Column('db_metadata', sa.JSON(), nullable=False),
    sa.Column('db_size_mb', sa.Float(), nullable=True),
    sa.Column('engine', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_history_connection_id'), 'database_history', ['connection_id'], unique=False)
    op.create_table('database_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('table_type', sa.String(length=50), nullable=True),
    sa.Column('schema', sa.String(length=255), nullable=True),
    sa.Column('engine', sa.String(length=255), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('data_size', sa.BigInteger(), nullable=True),
    sa.Column('index_size', sa.BigInteger(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_tables_id'), 'database_tables', ['id'], unique=False)
    op.create_table('database_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('table_name', sa.String(length=200), nullable=False),
    sa.Column('column_name', sa.String(length=200), nullable=False),
    sa.Column('data_type', sa.String(length=200), nullable=True),
    sa.Column('is_nullable', sa.Boolean(), nullable=True),
    sa.Column('is_primary_key', sa.Boolean(), nullable=True),
    sa.Column('is_unique', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('precision', sa.Integer(), nullable=True),
    sa.Column('scale', sa.Integer(), nullable=True),
    sa.Column('foreign_key', sa.JSON(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['database_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('database_table_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('table_type', sa.String(length=50), nullable=True),
    sa.Column('schema', sa.String(length=255), nullable=True),
    sa.Column('is_schema_changed', sa.Boolean(), nullable=True),
    sa.Column('engine', sa.String(length=255), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('data_size', sa.BigInteger(), nullable=True),
    sa.Column('index_size', sa.BigInteger(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('sync_id', sa.String(length=100), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['database_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_table_history_id'), 'database_table_history', ['id'], unique=False)
    op.create_table('column_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('table_history_id', sa.Integer(), nullable=True),
    sa.Column('column_id', sa.Integer(), nullable=True),
    sa.Column('sync_id', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=200), nullable=False),
    sa.Column('column_name', sa.String(length=200), nullable=False),
    sa.Column('data_type', sa.String(length=200), nullable=True),
    sa.Column('is_nullable', sa.Boolean(), nullable=True),
    sa.Column('is_primary_key', sa.Boolean(), nullable=True),
    sa.Column('is_unique', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('precision', sa.Integer(), nullable=True),
    sa.Column('scale', sa.Integer(), nullable=True),
    sa.Column('foreign_key', sa.JSON(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('column_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['database_columns.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ),
    sa.ForeignKeyConstraint(['table_history_id'], ['database_table_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('column_history')
    op.drop_index(op.f('ix_database_table_history_id'), table_name='database_table_history')
    op.drop_table('database_table_history')
    op.drop_table('database_columns')
    op.drop_index(op.f('ix_database_tables_id'), table_name='database_tables')
    op.drop_table('database_tables')
    op.drop_index(op.f('ix_database_history_connection_id'), table_name='database_history')
    op.drop_table('database_history')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_database_connections_id'), table_name='database_connections')
    op.drop_table('database_connections')
    # ### end Alembic commands ###
