"""main_db models

Revision ID: 16cabbcc08f0
Revises: 40c048fc423d
Create Date: 2026-01-03 11:54:08.097449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16cabbcc08f0'
down_revision: Union[str, Sequence[str], None] = '40c048fc423d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_history', sa.Column('enum_values', sa.JSON(), nullable=True))
    op.add_column('database_columns', sa.Column('enum_values', sa.JSON(), nullable=True))
    op.add_column('replica_column_history', sa.Column('enum_values', sa.JSON(), nullable=True))
    op.add_column('replica_database_columns', sa.Column('enum_values', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replica_database_columns', 'enum_values')
    op.drop_column('replica_column_history', 'enum_values')
    op.drop_column('database_columns', 'enum_values')
    op.drop_column('column_history', 'enum_values')
    # ### end Alembic commands ###
