"""main_db models

Revision ID: 40c048fc423d
Revises: bcdecba8c5be
Create Date: 2025-12-27 18:56:05.742689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c048fc423d'
down_revision: Union[str, Sequence[str], None] = 'bcdecba8c5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replica_database_columns', sa.Column('original_column_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'replica_database_columns', 'database_columns', ['original_column_id'], ['id'], ondelete='CASCADE')
    op.add_column('replica_database_connections', sa.Column('original_connection_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'replica_database_connections', 'database_connections', ['original_connection_id'], ['id'], ondelete='CASCADE')
    op.add_column('replica_database_constraints', sa.Column('original_constraint_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'replica_database_constraints', 'database_constraints', ['original_constraint_id'], ['id'], ondelete='CASCADE')
    op.add_column('replica_database_tables', sa.Column('original_table_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'replica_database_tables', 'database_tables', ['original_table_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'replica_database_tables', type_='foreignkey')
    op.drop_column('replica_database_tables', 'original_table_id')
    op.drop_constraint(None, 'replica_database_constraints', type_='foreignkey')
    op.drop_column('replica_database_constraints', 'original_constraint_id')
    op.drop_constraint(None, 'replica_database_connections', type_='foreignkey')
    op.drop_column('replica_database_connections', 'original_connection_id')
    op.drop_constraint(None, 'replica_database_columns', type_='foreignkey')
    op.drop_column('replica_database_columns', 'original_column_id')
    # ### end Alembic commands ###
