"""main_db models

Revision ID: 63c8cfbd36a9
Revises: 16cabbcc08f0
Create Date: 2026-01-03 19:36:25.248857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c8cfbd36a9'
down_revision: Union[str, Sequence[str], None] = '16cabbcc08f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_history', sa.Column('is_auto_increment', sa.Boolean(), nullable=True))
    op.add_column('column_history', sa.Column('is_unsigned', sa.Boolean(), nullable=True))
    op.add_column('database_columns', sa.Column('is_auto_increment', sa.Boolean(), nullable=True))
    op.add_column('database_columns', sa.Column('is_unsigned', sa.Boolean(), nullable=True))
    op.add_column('replica_column_history', sa.Column('is_auto_increment', sa.Boolean(), nullable=True))
    op.add_column('replica_column_history', sa.Column('is_unsigned', sa.Boolean(), nullable=True))
    op.add_column('replica_database_columns', sa.Column('is_auto_increment', sa.Boolean(), nullable=True))
    op.add_column('replica_database_columns', sa.Column('is_unsigned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replica_database_columns', 'is_unsigned')
    op.drop_column('replica_database_columns', 'is_auto_increment')
    op.drop_column('replica_column_history', 'is_unsigned')
    op.drop_column('replica_column_history', 'is_auto_increment')
    op.drop_column('database_columns', 'is_unsigned')
    op.drop_column('database_columns', 'is_auto_increment')
    op.drop_column('column_history', 'is_unsigned')
    op.drop_column('column_history', 'is_auto_increment')
    # ### end Alembic commands ###
