"""main_db models

Revision ID: a0b27dc6e4f0
Revises: 63c8cfbd36a9
Create Date: 2026-01-06 22:13:36.071745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b27dc6e4f0'
down_revision: Union[str, Sequence[str], None] = '63c8cfbd36a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_history', sa.Column('udt_name', sa.String(length=200), nullable=True))
    op.add_column('database_columns', sa.Column('udt_name', sa.String(length=200), nullable=True))
    op.add_column('replica_column_history', sa.Column('udt_name', sa.String(length=200), nullable=True))
    op.add_column('replica_database_columns', sa.Column('udt_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replica_database_columns', 'udt_name')
    op.drop_column('replica_column_history', 'udt_name')
    op.drop_column('database_columns', 'udt_name')
    op.drop_column('column_history', 'udt_name')
    # ### end Alembic commands ###
