"""main_db models

Revision ID: d341670481c4
Revises: 10adee122c3a
Create Date: 2025-11-19 21:19:11.682103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd341670481c4'
down_revision: Union[str, Sequence[str], None] = '10adee122c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database_connections', sa.Column('connection_uri', sa.Text(), nullable=True))
    op.add_column('database_connections', sa.Column('config', sa.JSON(), nullable=True))
    op.add_column('database_connections', sa.Column('db_metadata', sa.JSON(), nullable=True))
    op.add_column('database_connections', sa.Column('connection_status', sa.String(length=50), nullable=True))
    op.add_column('database_connections', sa.Column('last_connected_at', sa.DateTime(), nullable=True))
    op.add_column('database_connections', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('database_connections', sa.Column('auto_sync', sa.Boolean(), nullable=True))
    op.add_column('database_connections', sa.Column('sync_frequency', sa.String(length=30), nullable=True))
    op.add_column('database_connections', sa.Column('last_sync_at', sa.DateTime(), nullable=True))
    op.add_column('database_connections', sa.Column('next_sync_at', sa.DateTime(), nullable=True))
    op.add_column('database_connections', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('database_connections', sa.Column('updated_by', sa.String(length=100), nullable=True))
    op.add_column('database_connections', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    op.alter_column('database_connections', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('database_connections', 'db_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('database_connections', 'host',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('database_connections', 'username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=True)
    op.alter_column('database_connections', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('database_connections', 'database_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('database_connections', 'database_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('database_connections', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('database_connections', 'username',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('database_connections', 'host',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('database_connections', 'db_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('database_connections', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('database_connections', 'last_used_at')
    op.drop_column('database_connections', 'updated_by')
    op.drop_column('database_connections', 'created_by')
    op.drop_column('database_connections', 'next_sync_at')
    op.drop_column('database_connections', 'last_sync_at')
    op.drop_column('database_connections', 'sync_frequency')
    op.drop_column('database_connections', 'auto_sync')
    op.drop_column('database_connections', 'last_error')
    op.drop_column('database_connections', 'last_connected_at')
    op.drop_column('database_connections', 'connection_status')
    op.drop_column('database_connections', 'db_metadata')
    op.drop_column('database_connections', 'config')
    op.drop_column('database_connections', 'connection_uri')
    # ### end Alembic commands ###
