"""add constraint history

Revision ID: fb901b2ec214
Revises: 4a5ea2e0a57f
Create Date: 2025-12-25 10:05:04.186201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb901b2ec214'
down_revision: Union[str, Sequence[str], None] = '4a5ea2e0a57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('schema', sa.String(length=200), nullable=True),
    sa.Column('table_name', sa.String(length=200), nullable=False),
    sa.Column('constraint_name', sa.String(length=200), nullable=True),
    sa.Column('constraint_type', sa.String(length=50), nullable=True),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('referenced_table', sa.String(length=200), nullable=True),
    sa.Column('referenced_columns', sa.JSON(), nullable=True),
    sa.Column('on_delete', sa.String(length=50), nullable=True),
    sa.Column('on_update', sa.String(length=50), nullable=True),
    sa.Column('is_deferrable', sa.Boolean(), nullable=True),
    sa.Column('initially_deferred', sa.Boolean(), nullable=True),
    sa.Column('using_index', sa.Boolean(), nullable=True),
    sa.Column('index_name', sa.String(length=200), nullable=True),
    sa.Column('check_expression', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('constraint_order', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['database_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constraint_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('table_history_id', sa.Integer(), nullable=True),
    sa.Column('constraint_id', sa.Integer(), nullable=True),
    sa.Column('sync_id', sa.String(length=100), nullable=False),
    sa.Column('schema', sa.String(length=200), nullable=True),
    sa.Column('table_name', sa.String(length=200), nullable=False),
    sa.Column('constraint_name', sa.String(length=200), nullable=True),
    sa.Column('constraint_type', sa.String(length=50), nullable=True),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('referenced_table', sa.String(length=200), nullable=True),
    sa.Column('referenced_columns', sa.JSON(), nullable=True),
    sa.Column('on_delete', sa.String(length=50), nullable=True),
    sa.Column('on_update', sa.String(length=50), nullable=True),
    sa.Column('is_deferrable', sa.Boolean(), nullable=True),
    sa.Column('initially_deferred', sa.Boolean(), nullable=True),
    sa.Column('using_index', sa.Boolean(), nullable=True),
    sa.Column('index_name', sa.String(length=200), nullable=True),
    sa.Column('check_expression', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('constraint_order', sa.Integer(), nullable=True),
    sa.Column('constraint_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ),
    sa.ForeignKeyConstraint(['constraint_id'], ['database_constraints.id'], ),
    sa.ForeignKeyConstraint(['table_history_id'], ['database_table_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('column_history', 'constraints')
    op.drop_column('database_columns', 'constraints')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database_columns', sa.Column('constraints', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('column_history', sa.Column('constraints', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('constraint_history')
    op.drop_table('database_constraints')
    # ### end Alembic commands ###
